#!/bin/sh

# if [ "$1" = "twm"  -o "$1" = "flwm" ]; then
#     $HOME/.dzen/bin/status | dzen2 -p -ta l -w 1160 -h 13 -bg gray15 -fn '-*-terminus-medium-r-normal--12-*' -e 'onexit=ungrabmouse' &
#     trayer --expand false --alpha 20  --tint 0x606060 --transparent true --padding 1 --margin 0 --edge top --align right --SetDockType true --SetPartialStrut true --heighttype pixel --height 7 --widthtype pixel --width 120 &
#     #sleep 20 && wbar -above-desk -bpress -isize 45 -balfa 20 -nanim 9 &
#     if [ -f $HOME/.fehbg ]; then
#         $HOME/.fehbg &
#     else
#         feh --bg-max ~/.wallpaper &
#     fi
#     tint2 &
# fi

start_wm() {
    local wm="${1}"
    local DEFAULT_SESSION="dwm"
    if [ -n ${wm} ]; then
        export USERWM=${wm}
        case ${USERWM} in
            xfce)         exec ck-launch-session dbus-launch --exit-with-session startxfce4 ;;
            fluxbox)      exec ck-launch-session dbus-launch --exit-with-session startfluxbox ;;
            fvwm|fvwm2)   exec ck-launch-session dbus-launch --exit-with-session fvwm2 ;;
            fvwm-themes*) exec ck-launch-session dbus-launch --exit-with-session fvwm-themes-start -s sa ;;
            dwm)          exec ck-launch-session dbus-launch --exit-with-session $HOME/.dwm/startdwm ;;
            kde)          exec ck-launch-session dbus-launch --exit-with-session startkde5 ;;
            gnome)        exec ck-launch-session dbus-launch --exit-with-session gnome-session ;;
            mate)         exec ck-launch-session dbus-launch mate-session ;;
            rox)          exec ck-launch-session dbus-launch --exit-with-session rox -S ;;
            lainwm)       exec ck-launch-session dbus-launch --exit-with-session lainwm ;;
            openbox)      exec ck-launch-session dbus-launch --exit-with-session openbox-session ;;
            windowmaker)  exec ck-launch-session dbus-launch --exit-with-session wmaker ;;
            mate)         exec ck-launch-session dbus-launch --exit-with-session mate-session ;;
            metisse)      exec ck-launch-session dbus-launch --exit-with-session metisse-start-fvwm ;;
            lxde)      exec dbus-launch --exit-with-session ck-launch-session startlxde ;;
            wm)   exec sbcl --script ~/.emacs.d/vendor/github.com/mgi/wm/wm.lisp ;;
            cwm)   exec dbus-launch --exit-with-session ck-launch-session cwm ;;
            i3)   exec dbus-launch --exit-with-session ck-launch-session i3 ;;
            twm)
                vdesk &
                exec dbus-launch --exit-with-session ck-launch-session twm ;;
            bspwm)
                sxhkd &
                exec bspwm
                ;;
            lumina)
                exec Lumina-DE ;;
            maxwelm)
                exec maxwelm ;;
            *)            exec dbus-launch --exit-with-session ck-launch-session $1 ;;
        esac
    else
        exec ck-launch-session dbus-launch --exit-with-session  $DEFAULT_SESSION
    fi
}
