#!/usr/bin/env sh

server=lammas
user=$1
root=/Volumes

echo "mount MyPassport" 
sudo mount_nfs -o soft $server:/Volumes/MyPassport $root/mypassport
echo "mount Deskstar"
sudo mount_nfs -o soft $server:/Volumes/Deskstar   $root/deskstar
echo "mount lammas"
sudo mount_nfs -o soft $server:/Users/$user $root/lammas
