#!/bin/sh

set -o nounset

DEFAULT_NAMESPACE="user"
GETEXTATTR="getextattr -q ${DEFAULT_NAMESPACE}"
SETEXTATTR="setextattr -q ${DEFAULT_NAMESPACE}"
LSEXTATTR="lsextattr -q ${DEFAULT_NAMESPACE}"
RMEXTATTR="rmextattr -q ${DEFAULT_NAMESPACE}"

# get attribute
get_attr() {
    local name="${1}"
    local file="${2}"
    local value="$(${GETEXTATTR} ${name} ${file})"

    if test -n "${value}"
    then
        printf "%s -> %s\n" "${name}" "${value}"
    fi
}

# set attribute
set_attr() {
    local name="${1}"
    local value="${2}"
    local file="${3}"

    ${SETEXTATTR} "${name}" "${value}" "${file}"
}

# list attributes
ls_attr() {
    local file="${1}"
    ls_attr_user "${file}"
}

ls_attr_user() {
    local file="${1}"
    local attrs="$(${LSEXTATTR}  ${file})"

    if test -n "${attrs}"
    then
        printf "${DEFAULT_NAMESPACE}:\n"

        for n in ${attrs}
        do
            ls_attr_user_print "${n}" "${file}"
        done
    fi
}

ls_attr_user_print() {
    local name="${1}"
    local file="${2}"
    local value="$(${GETEXTATTR}  ${name} ${file})"

    printf "     %s -> %s\n" "${name}" "${value}"
}

# remove attribute
rm_attr() {
    local name="${1}"
    local file="${2}"

    ${RMEXTATTR}  ${name}  "${file}"
}

usage() {
    printf "subcommands:\n"
    printf "\tset name value file\n"
    printf "\tget name file\n"
    printf "\tls file\n"
    printf "\trm name file\n"
    printf "example:\n"
    printf "\txat set lang tcsh .tcshrc\n"
    printf "\txat get lang .tcshrc\n"
    printf "\txat set place home .tcshrc\n"
    printf "\txat ls .tcshrc\n"
    printf "\txat rm lang .tcshrc\n"
    printf "\txat ls .tcshrc\n"
}

main() {
    local command="${1}"
    shift 1
    if test -z ${command}
    then
        usage
    else
        case ${command} in
            get)
                get_attr "${@}" ;;
            set)
                set_attr "${@}" ;;
            ls)
                ls_attr "${@}";;
            rm)
                rm_attr "${@}";;
        esac
    fi
}

main "${@}"
