#!/bin/sh

~/.fehbg &
xcompmgr -n &
#mmaker -f FluxBox &
#fluxbox-generate_menu -g -k -ds -is
conky -c /usr/home/mytoh/.fluxbox/conkyrc &

exec fluxbox &
# start apps after fluxbox started
fbpid=$!
sleep 1
{
  # ipager &
  true &
} &
wait $fbpid
