#!/bin/sh

~/.fehbg &
xcompmgr -n &
mmaker -f FluxBox &
conky -c /usr/home/mytoh/.fluxbox/conkyrc &

exec fluxbox &
# start apps after fluxbox started
fbpid=$!
sleep 1
{
  # ipager &
  true &
} &
wait $fbpid
