alias spc2ubar='command gosh space2underbar.scm'
alias ea='command gosh extattr.scm'

alias pk='gosh run-pikkukivi.scm'
alias rr='pk rm'
alias nap='pk napa'
alias tk='pk talikko'
alias pahvi='pk pahvi'
alias unpack='pk unpack'
alias futaba='pk futaba'
alias yotsuba='pk yotsuba'
alias gsi='rlwrap gosh run-pk.scm repl'
alias ls='pk ls -d'
alias la='pk ls -d -a'
alias ll='pk ls -d -ptsf'
alias lla='pk ls -d -ptsf -a'
alias l='pk ls -d'
alias emma='pk emma'
alias sgit='pk ääliö'
alias colour-numbers='pk colour numbers'
alias colour-pacman='pk colour pacman'
alias colour-spect='pk colour spect'
alias colour-square='pk colour square'
alias topless='pk topless'
alias radio='pk radio listen'
alias radio-list='pk radio list'
alias mkd='pk mkd'
alias gsp='pk gsp'
alias tm='pk tm'
alias aa='pk ascii-taide'
alias starwars='pk starwars'
alias jblive='pk jblive'
alias sumo='pk sumo'
alias sumo2='pk sumo2'
alias sumo3='pk sumo3'
alias sssh='pk sssh'
alias sget='pk sget'
alias a='pk launch-app'

# taken from oh-my-zsh
# Source: http://aur.archlinux.org/packages/lolbash/lolbash/lolbash.sh
alias wtf='dmesg'
alias onoz='cat /var/log/errors.log'
alias rtfm='man'

alias visible='echo'
alias invisible='cat'
alias moar='more'
alias tldr='less'
alias alwayz='tail -f'

alias icanhas='mkdir'
alias gimmeh='touch'
alias donotwant='rm'
alias dowant='cp'
alias gtfo='mv'
alias nowai='chmod'

alias hai='cd'
alias iz='ls'
alias plz='pwd'
alias ihasbucket='df -h'

alias inur='locate'
alias iminurbase='finger'

alias btw='nice'
alias obtw='nohup'

alias nomz='ps -aux'
alias nomnom='killall'

alias byes='exit'
alias cya='reboot'
alias kthxbai='halt'
