#!/usr/bin/env gosh

; http://d.hatena.ne.jp/rui314/20070604/p1
;
; - added modules in 0.9.2
; -
(require "binary/ftype")
(require "binary/io")
(require "binary/pack")
(require "compat/jfilter")
(require "compat/norational")
(require "compat/stk")
(require "control/job")
(require "control/thread-pool")
(require "crypt/bcrypt")
(require "dbd/null")
(require "dbi")
(require "dbm")
(require "dbm/fsdbm")
(require "dbm/ndbm")
(require "file/filter")
(require "file/util")
(require "gauche-init")
(require "gauche/array")
(require "gauche/auxsys")
(require "gauche/cgen")
(require "gauche/cgen/cise")
(require "gauche/cgen/literal")
(require "gauche/cgen/precomp")
(require "gauche/cgen/stub")
(require "gauche/cgen/tmodule")
(require "gauche/cgen/type")
(require "gauche/cgen/unit")
(require "gauche/charconv")
(require "gauche/collection")
(require "gauche/common-macros")
(require "gauche/condutil")
(require "gauche/config")
(require "gauche/defvalues")
(require "gauche/dictionary")
(require "gauche/experimental/app")
(require "gauche/experimental/lamb")
(require "gauche/experimental/ref")
(require "gauche/fcntl")
(require "gauche/fileutil")
(require "gauche/generator")
(require "gauche/hashutil")
(require "gauche/hook")
; (require "gauche/interactive")
; (require "gauche/interactive/info")
(require "gauche/interpolate")
; (require "gauche/let-opt") ;
(require "gauche/libutil")
(require "gauche/listener")
(require "gauche/logger")
(require "gauche/logical")
(require "gauche/macroutil")
(require "gauche/matrix")
(require "gauche/modutil")
(require "gauche/mop/instance-pool")
(require "gauche/mop/propagate")
(require "gauche/mop/singleton")
(require "gauche/mop/validator")
(require "gauche/net")
(require "gauche/numerical")
(require "gauche/package")
(require "gauche/package/build")
(require "gauche/package/compile")
(require "gauche/package/fetch")
(require "gauche/package/util")
(require "gauche/parameter")
(require "gauche/parseopt")
(require "gauche/partcont")
(require "gauche/portutil")
(require "gauche/procedure")
(require "gauche/process")
(require "gauche/record")
(require "gauche/redefutil")
(require "gauche/regexp")
(require "gauche/reload")
(require "gauche/selector")
(require "gauche/sequence")
(require "gauche/serializer")
; (require "gauche/serializer/aserializer") ; syntax error
(require "gauche/signal")
; (require "gauche/singleton")
(require "gauche/sortutil")
(require "gauche/stringutil")
(require "gauche/syslog")
(require "gauche/termios")
(require "gauche/test")
(require "gauche/threads")
(require "gauche/time")
(require "gauche/treeutil")
(require "gauche/uvector")
; (require "gauche/validator")
(require "gauche/version")
(require "gauche/vm/debugger")
(require "gauche/vm/insn-core")
(require "gauche/vm/insn")
(require "gauche/vm/profiler")
(require "gauche/vport")
(require "math/const")
(require "math/mt-random")
; (require "os/windows")
(require "parser/peg")
(require "rfc/822")
(require "rfc/base64")
(require "rfc/cookie")
(require "rfc/ftp")
(require "rfc/hmac")
(require "rfc/http")
(require "rfc/icmp")
(require "rfc/ip")
(require "rfc/json")
(require "rfc/md5")
(require "rfc/mime")
(require "rfc/quoted-printable")
(require "rfc/sha")
(require "rfc/sha1")
(require "rfc/uri")
; (require "rfc/zlib")  ; cannot find libz.so.5
(require "slib")
(require "srfi-0")
(require "srfi-1")
(require "srfi-11")
(require "srfi-13")
(require "srfi-14")
(require "srfi-14/query")
(require "srfi-14/set")
(require "srfi-19")
(require "srfi-26")
(require "srfi-29/bundle")
(require "srfi-29/format")
(require "srfi-27")
(require "srfi-29")
(require "srfi-31")
(require "srfi-37")
(require "srfi-4")
(require "srfi-42")
(require "srfi-43")
(require "srfi-5")
(require "srfi-55")
(require "srfi-60")
(require "srfi-7")
(require "srfi-9")
(require "srfi-98")
(require "sxml/adaptor")
(require "sxml/serializer")
(require "sxml/ssax")
(require "sxml/sxpath")
(require "sxml/to-html")
(require "sxml/tools")
(require "sxml/tree-trans")
(require "text/csv")
(require "text/diff")
(require "text/gettext")
(require "text/html-lite")
(require "text/info")
(require "text/parse")
(require "text/progress")
(require "text/sql")
(require "text/tr")
(require "text/tree")
(require "text/unicode")
(require "util/combinations")
(require "util/digest")
(require "util/isomorph")
(require "util/lcs")
(require "util/list")
(require "util/match")
(require "util/queue")
(require "util/rbtree")
(require "util/record")
(require "util/relation")
(require "util/sparse")
(require "util/stream")
(require "util/toposort")
(require "util/tree")
(require "util/trie")
(require "www/cgi-test")
(require "www/cgi")
(require "www/cgi/test")

; personal library
(require "kirjasto")
(require "panna")


(use srfi-1)
(use file.util)

;; カレントモジュールが継承しているモジュールで定義されている変数と、
;; その他のモジュールがエクスポートしている変数を出力する。
(define (main args)
  (define (register lister modules)
    (for-each (lambda (mod)
                (for-each (cut hash-table-put! ht <> #t)
                          (lister mod)))
              modules))
  (define ht (make-hash-table))
  (register (lambda (mod)
              (hash-table-keys (module-table mod)))
            (module-precedence-list (current-module)))
  (register module-exports
            (all-modules))

  ; (for-each print
  ; (sort (map symbol->string (hash-table-keys ht)))))



  ;; -- added
  (let ((completion-file (open-output-file
                           (build-path
                             (or  (sys-getenv "RLWRAP_HOME")
                               (home-directory)) 
                             "gosh_completions"))))
    (for-each (lambda (s)
                (display s completion-file)
                (newline  completion-file))
              (sort (map symbol->string (hash-table-keys ht))))
    )
  0)

