#!/usr/bin/env sh

server=192.168.1.11
user=$1


echo "mount MyPassport" 
sudo mount -o soft $server:/Volumes/MyPassport /nfs/mypassport
echo "mount Deskstar"
sudo mount -o soft $server:/Volumes/Deskstar   /nfs/deskstar
echo "mount quatre"
sudo mount -o soft $server:/Users/$user /nfs/quatre
