#!/usr/bin/env sh

server=192.168.1.11
user=$1
root=/Volumes

echo "mount MyPassport" 
sudo mount -o soft $server:/Volumes/MyPassport $root/mypassport
echo "mount Deskstar"
sudo mount -o soft $server:/Volumes/Deskstar   $root/deskstar
echo "mount quatre"
sudo mount -o soft $server:/Users/$user $root/quatre
