#!/usr/bin/env bash

 startdwm()
{
  if [ -x $HOME/.fehbg ]; then
    $HOME/.fehbg &
  fi
  xcompmgr -n &

  while true; do
    cpu(){
      cpu=$(top -b -d 2 | grep ^CPU | awk '{print $2,$6}')
      echo "${cpu}"
    }
    sep=`echo -e "\x03|\x01"`
    diskused=$(df -ch | grep total | awk '{print $3}' | cut -c 1-3)
    disktotal=$(df -ch | grep total | awk '{print $2}')
    freemem=$(vmstat -h |grep -n 2| awk '{print $6}')
    ip=$(curl ifconfig.me 2>/dev/null)
    xsetroot -name "$(cpu) ${sep}:: $freemem :: $diskused/$disktotal :: $ip :: $(date +"%F %R")"
    done &

  while true; do
   dwm || exit
  done
}

startdwm
